### PR TITLE
Install NumPy through SciPy's dependency on it

### LINKED ISSUE #224: loosen numpy requirements for non-extra installs
# Description

we are pretty restrictive in the numpy version range due to trying to conform to TF's valid range, but TF is only one of the backends. If just installing `pip install pyhf` we should not force users to a speciic range unless we require the APIs

`numpy>=1.14.0` should be enough unless i'm missing something. @kratsg since you changed this last, any reason you see to restrict numpy further?

### PR DESCRIPTION
**Pull request by matthewfeickert**
Resolves #224. See [this SO question](https://stackoverflow.com/questions/52192492/possible-to-have-setuptools-extras-require-override-requirement-from-install-req) for more details.

As `scipy` is an installation requirement of `pyhf` then as `scipy` requires `numpy` the latest release of `numpy` from PyPI will be installed if `pyhf` is installed in the default manner. However, if an optional setup is requested through `extra_require` and that setup has `numpy` constraints those constraints will be implemented.

So

```
pip install .
```

installs the latest `numpy` release

and

```
pip install .[tensorflow]
```

installs `numpy` as constrained by `tensorflow`.

# Checklist Before Requesting Approver

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request

### CODE REVIEW

**Comment by matthewfeickert** [comment]
This is currently failing the CI, so I need to check to see what I missed and then fix it (or this might not work out as I thought).

**Comment by kratsg** [comment]
Extra spaces need to be added. It needs to match exactly as a string. Doctesting is done by comparing stdouts.

**Comment by matthewfeickert** [comment]
Yes. I pushed just before leaving to catch the bus, so I hadn't checked the logs yet.

**Comment by matthewfeickert** [comment]
Everything is passing for Python 3.6 (:+1:) but Python 2.7 is now failing on the papermill tests

```
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
```

**Comment by kratsg** [comment]
> Everything is passing for Python 3.6 (👍) but Python 2.7 is now failing on the papermill tests

Conflicting python package installations? E.G. a fix when I've seen that before is to do `pip install --upgrade numpy`.

**Comment by matthewfeickert** [comment]
> A fix when I've seen that before is to do `pip install --upgrade numpy`

Yes, that's what everyone seems to recommend, but I'm trying to understand _why_ that is. Though that might not be a good use of time. I've cleared all the caches just to make sure this isn't an issue there, and if that still fails then I'll try adding the upgrade thing to the CI (reluctantly).

**Comment by kratsg** [comment]
> Yes, that's what everyone seems to recommend, but I'm trying to understand why that is. Though that might not be a good use of time. I've cleared all the caches just to make sure this isn't an issue there, and if that still fails then I'll try adding the upgrade thing to the CI (reluctantly).

conflicts of versions between `pip install .` and `pip install .[develop,....]`?

**Comment by matthewfeickert** [comment]
> conflicts of versions between `pip install .` and `pip install .[develop,....]`?

I don't think so, as we only ever do

```
pip install -U -q -e .[develop,tensorflow,mxnet,torch]
```
in the CI.

**Comment by lukasheinrich** [comment]
that's pretty clever. if we can get tests to pass

**Comment by matthewfeickert** [comment]
Hm, so Python 2.7 on Travis continues to be a bit confusing as if numpy is upgraded, then it is upgraded from `1.14.5` to `1.15.1`, which then causes the RuntimeError above to be resolved (though now the version is in conflict with the latest accepted for `tensorflow` and `mxnet`) but then the doctest fails. :upside_down_face: I guess this going to involve some more thinking about how Travis has things setup.

**Comment by matthewfeickert** [comment]
Should be ready for review now. Let me know if you have questions.

**Comment by matthewfeickert** [comment]
The above confusion I was having is resolved in PR #237.

**Comment by lukasheinrich** [comment]
this made the docker image work

```
%  cat << 'EOF' | docker run -i pyhf/pyhf pyhf cls
{               
    "channels": [
        {
            "name": "channel1",
            "samples": [
                {"name": "sig", "data": [ 5.0], "modifiers": [{"name": "mu","data": null, "type": "normfactor"}]},
                {"name": "bkg", "data": [50.0], "modifiers": []}
            ]
        }
    ],
    "data": {"channel1": [51.0] },
    "toplvl": {
        "measurements": [
          {"config": {"poi": "mu"}, "name": "HelloWorld"}
        ]
    }
}
EOF
{
    "CLs_exp": [
        0.15948986298223164, 
        0.29000867372064876, 
        0.4934558602497132, 
        0.741297207488922, 
        0.9268610639479048
    ], 
    "CLs_obs": 0.5268665657158867
}
```

thanks @matthewfeickert

**Pull request merged**
