### PR TITLE
Add --version option to the CLI

### LINKED ISSUE #306: Add --version flag to pyhf CLI
# Description

As [suggested by Lukas](https://github.com/diana-hep/pyhf/pull/304#issuecomment-428856809), adding a `--version` flag to the pyhf CLI could be useful.

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

Resolves #306 

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

The PR title should suffice

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Now from the CLI

```
$ pyhf --version
pyhf, version 0.0.15
```

I've noticed that this seems pretty slow (multiple seconds) though. Not sure if anyone has thoughts on this.

**Comment by lukasheinrich** [comment]
it might be related to us importing lots of modules .. if we move these imports into the function itself we might mitigate that.. however that seems a bit hacky.. not sure what the best way is to lazily import modules. @kratsg any ideas?

**Comment by lukasheinrich** [comment]
https://github.com/mnmelo/lazy_import ?

**Comment by matthewfeickert** [comment]
>  if it's OK, i'll merge this

Sounds good. Can you open up an Issue for the loading time once you do though?

**Pull request merged**
