### PR TITLE
docs: Use consistent style in docstrings

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

Should be done _after_ PR #588 is merged.

Amend the docstrings added in PR #558.

- Some docstrings that were added in https://github.com/diana-hep/pyhf/commit/4e5acc3f8fc86da6f8e0cb0a795c24ab494c02de somehow got removed from the final PR
- For methods that are repeated across distributions use the same docstring for consistency
- Additionally fix some typos

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* docs: Amend the docstrings for the probability module to include missing docstrings and fix typos and enforce consistency
* tests: Add probability module to pydocstyle testing
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Build of docs are here: https://pyhf-staging.readthedocs.io/en/fix-correct-typos-in-docstrings/api.html#probability-distribution-functions-pdfs

**Comment by kratsg** [comment]
This will need to get updated after my requested changes are in.

**Comment by matthewfeickert** [comment]
> This will need to get updated after my requested changes are in.

You mean for the `D1` vs. `D107` comment with pydocstyle [in PR #588](https://github.com/diana-hep/pyhf/pull/588#discussion_r330639228)?

**Comment by kratsg** [comment]
> You mean for the `D1` vs. `D107` comment with pydocstyle [in PR #588](https://github.com/diana-hep/pyhf/pull/588#discussion_r330639228)?

No, for changes to the docstrings themselves.

**Comment by matthewfeickert** [comment]
> No, for changes to the docstrings themselves.

Oh, when you said

> ... after my requested changes are in.

You mean that you haven't made them yet.

**Comment by matthewfeickert** [comment]
> This will need to get updated after my requested changes are in.

@kratsg while I want this to go in after PR #588 as that is going to add `pydocstyle` can you add your requested changes for these now so that I can address them and have this ready to go?

**Pull request merged**
