### PR TITLE
Use papermill versions compatible with v1.0 and add scrapbook

### LINKED ISSUE #419: Determine if papermill v1.0 API change is a problem
# Description

The [papermill `v1.0` release will introduce API breaking changes](https://github.com/nteract/papermill/blob/d554193bc458797b63af1f94964883d5dcca2418/README.md). It would be good to determine if these changes will matter for pyhf testing and require the addition of [scrapbook](https://nteract-scrapbook.readthedocs.io/en/latest/) or if the API change doesn't affect pyhf.

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

Resolves #419 

This PR updates to use papermill releases compatible with the [`v1.0.0`](https://pypi.org/project/papermill/1.0.0/) API. As part of that it also adds [nteract's scrapbook](https://github.com/nteract/scrapbook) as a dependency to replace papermill's [deprecated `pm.record` API](https://github.com/nteract/papermill/blob/d554193bc458797b63af1f94964883d5dcca2418/README.md#recording-values-to-the-notebook) with the [`scrapbook.glue` API](https://github.com/nteract/scrapbook/blob/96eab395e68069d5e775f01d587e16ef7ce39e01/README.md#glue-to-persist-scraps).

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Update papermill dependency to use releases compatible with v1.0
* Add scrapbook dependency to use the glue API to replace pm.record
   - https://github.com/nteract/scrapbook
   - https://github.com/nteract/papermill/blob/d554193bc458797b63af1f94964883d5dcca2418/README.md#recording-values-to-the-notebook
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
This is passing all the test, but I want to wait until Issue #456 is resolved before this goes in.

**Comment by matthewfeickert** [comment]
Once this is approved ping me before merging it in.

**Comment by lukasheinrich** [comment]
@matthewfeickert ping!

**Comment by matthewfeickert** [comment]
@lukasheinrich Thanks. :) I had just wanted to check more about the glue API, but it seems that's all I need to do.

**Pull request merged**
