### PR TITLE
Add Git pre-commit hook install to CONTRIBUTING

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

Add the installation of the git pre-commit hook as part of the recommendations for contributing a PR. Additionally, update the [Black](https://github.com/psf/black) link endpoint to reflect that Black is now part of the Python Software Foundation :tada: &mdash; where it is now maintained for the whole community by awesome people like Carol Willing. :rocket: 

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Add installation of pre-commit for Git pre-commit hook to development recommendations in CONTRIBUTING
```

### CODE REVIEW

**Comment by lukasheinrich** [comment]
thanks for this!

**Comment by lukasheinrich** [comment]
@matthewfeickert maybe we should also link to the `developing` section in the docs?

**Comment by matthewfeickert** [comment]
> @matthewfeickert maybe we should also link to the `developing` section in the docs?

I do this in the PR. Where are you suggesting that I link _from_?

**Comment by lukasheinrich** [comment]
ah sorry missed this.. sorry for the noise

**Comment by lukasheinrich** [comment]
happy to merged after CI

**Pull request merged**
