### PR TITLE
make installation editable

### PR DESCRIPTION
**Pull request by lukasheinrich**
# Description

Make binder postBuild install editable.

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request

### CODE REVIEW

**Comment by kratsg** [comment]
Don't you want a `pip install -e .[develop]`?

**Comment by lukasheinrich** [comment]
hm good question, it's not really intended to be a development environment but we probably do want a "best of class" installation that has all features we can demo, and `[develop]` should prob gives us that..

**Comment by kratsg** [comment]
LGTM.

**Comment by matthewfeickert** [comment]
Yeah, LGTM (obviously). I'll leave this to @lukasheinrich merge this in though in the event that he has anything else that he wanted to do.

Oh, along these lines, @lukasheinrich is there anything else that you wanted to do on the _very  nice_ demo notebook that is in the [`binderdemo`](https://github.com/diana-hep/pyhf/tree/binderdemo) branch? Or can we start a PR for that to be brought into `master` as well?

**Comment by lukasheinrich** [comment]
I think that's it, we need to only merge in the demo notebook, I'll do a PR soon.

**Pull request merged**
