### PR TITLE
notebook

### PR DESCRIPTION
**Pull request by lukasheinrich**
# Description

adds the demo notebook we prepared for the CERN Binder Talk.

# Checklist Before Requesting Approver

- [ ] Tests are passing
- [x] "WIP" removed from the title of the pull request

### CODE REVIEW

**Comment by kratsg** [comment]
Not too much to comment but this adds a ROOT file -- we're ok with that?

**Comment by lukasheinrich** [comment]
Yeah, I wouldn't add binary data for the core repo, but for the validation and examples directory I think it's ok

**Comment by kratsg** [comment]
LGTM.

**Comment by kratsg** [comment]
I'll go ahead and merge this in now as @matthewfeickert did express interest in having this moved over, and this isn't too bad.

**Pull request merged**
