### PR TITLE
Add citations and use cases to website

### LINKED ISSUE #315: Add papers that use pyhf section to website
# Description

Now that 

L. Heinrich, H. Schulz, J. Turner and Y. Zhou, _[Constraining $A_{4}$ Leptonic Flavour Model Parameters at Colliders and Beyond](https://inspirehep.net/record/1698425)_, 2018

is out and cites `pyhf` it would be good to add a page to the website of papers that cite use of `pyhf`.

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

Resolves #315 

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

The PR title should suffice

### CODE REVIEW

**Comment by matthewfeickert** [comment]
This is what the result looks like

use_case_and_citations_view

I'm not sure how to get Sphinx to both use the Bibtex system and understand how to render LaTeX in math mode (with regards to the `$A_{4}$`).

Also feedback RE: the text on the page and placement in the main menu is welcomed.

**Comment by kratsg** [comment]
> I'm not sure how to get Sphinx to both use the Bibtex system and understand how to render LaTeX in math mode (with regards to the `$A_{4}$`).

Seems to be an open issue in mcmtroffaes/sphinxcontrib-bibtex#114 . Although thinking about it, you might be able to (in some cases) get away with the latin encoding `:encoding: latin` but not fully sure how much. Since it all supports unicode, can possible put unicode in directly.

**Comment by lukasheinrich** [comment]
https://www.unicodeit.net/

**Comment by matthewfeickert** [comment]
> https://www.unicodeit.net/

Thanks Kyle and Sven! :) A₄

**Pull request merged**
