### PR TITLE
Use TensorFlow Probability for distributions

### LINKED ISSUE #297: Memory Being Exceeded in Travis for Unclear Reasons
# Description

When trying to use `tfp` for distributions the tests for the notebooks will run, but then there will be a corde dump given that the memory on Travis is being exceeded. This is highly confusing as there is nothing strange being done and this occurs even with `sudo: required` which [grants 7.5 GB of memory on the Ubuntu Trusty machines](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system). This has been [shown to happen even if only the hello world notebook is run](https://github.com/diana-hep/pyhf/pull/296/commits/cc9ffdbb4fcae542074c3a32ea47c742fbb7b928) so this seems to be some very strange behavior.

# Expected Behavior

pyhf and its dependencies should be able to be loaded into memory without issues.

# Actual Behavior

When running any notebook with papermill a [core dump occurs](https://travis-ci.org/diana-hep/pyhf/jobs/437729184#L689-L691)

```
===================== 1 passed, 3 warnings in 6.91 seconds =====================
*** Error in `/home/travis/virtualenv/python2.7.14/bin/python': corrupted size vs. prev_size: 0x00000000031198f0 ***
/home/travis/.travis/job_stages: line 98:  4350 Aborted                 (core dumped) pytest tests/test_notebooks.py
```

# Steps to Reproduce

c.f. PR #296 

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

[TensorFlow Probability](https://www.tensorflow.org/probability/) is going to be where all developments for probabilistic distributions and sampling in TensorFlow will be implemented, so it is important to switch to using it over the `contrib` modules.

There are additional issues with Travis and memory footprints that this PR exposes, and may need to be resolved in another PR as they go beyond this scope. Resolves #297.

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Related to the issues that are being seen with testing the notebooks are the following Issues:
- https://github.com/astropy/astropy/issues/6025
- https://github.com/cython/cython/issues/1720

**Comment by kratsg** [comment]
The malloc errors are fixable with additional `before_install` on the travis images:

```yaml
- sudo apt-get install libtcmalloc-minimal4
- export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"
```

This is inspired from r9y9/gantts#14 but is also something I've had to do about 4 years ago.

See the results of adding this in this [travis job](https://travis-ci.org/diana-hep/pyhf/jobs/437889258) on the [revise/use-tfp-for-distributions_gstark](https://github.com/diana-hep/pyhf/commits/revise/use-tfp-for-distributions_gstark) branch.

**Comment by matthewfeickert** [comment]
@kratsg Huge thanks on this! I had been poking around for a long time, and as pointed out in https://github.com/astropy/astropy/issues/6025 this is an upstream Cython thing as you said, but I wasn't sure how to fix it to stop the core dumps. Thanks for stepping in with another awesome fix. :)

**Comment by matthewfeickert** [comment]
Proposed commit log:

- Use TensorFlow Probability for distributions in the TensorFlow backend
- Add tensorflow-probability as a dependency of the tensorflow install environment
- Use libtcmalloc-minimal4 to avoid a memory problem on Travis with Cython that results in core dumps
- Add docstrings to poisson_logpdf and normal_logpdf

**Pull request merged**
