### PR TITLE
Apply recommended changes for CodeFactor issues

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

This is simply a cleaning PR that goes through and addresses most of the "issues" that CodeFactor finds (though it leaves all the cylic import issues because those [can't be dealt with as long as we still have Python 2](https://github.com/diana-hep/pyhf/issues/469#issuecomment-511637392)).

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Apply recommended changes from CodeFactor's pylint linter
   - Removal of unnecessary pass
   - Removal of unnecessary return (Python returns None if there is no return statement)
   - Removal of len to check if list or dict is empty (empty arrays and empty dict evaluate to False in Python)
   - Use 'is' for singleton comparison (c.f. https://www.python.org/dev/peps/pep-0008/#programming-recommendations)
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
As these are essentially all just style changes that were suggested by a linter I am more then happy to drop any of them.

**Comment by matthewfeickert** [comment]
Additionally, if you feel there should be more explanation in the commit message I'm happy to extend it.

**Comment by lukasheinrich** [comment]
this looks great. I went over this but I hope there are also some guarantees in CF that make sure the suggestions don't change functionality. But looking it over it seems find. Thanks!

**Comment by matthewfeickert** [comment]
>...I hope there are also some guarantees in CF that make sure the suggestions don't change functionality.

I don't think there is any guarantee, but for the sake of completeness I'll break down the major changes that are implemented here.

- Removal of unnecessary `pass`
- Removal of unnecessary `return` (Python returns `None` if there is no `return` statement)
- Removal of `len` to check if `list` or `dict` is empty (empty arrays and empty dict evaluate to False in Python)
```
>>> bool([])
False
>>> bool({})
False
>>> not []
True
>>> not {}
True
```
- Use `is` for singleton comparison (c.f. https://www.python.org/dev/peps/pep-0008/#programming-recommendations)

Given this, we shouldn't see any change in evaluation behavior. As the CI is passing I believe all changes to be safe enough.

**Pull request merged**
