### PR TITLE
RECAST example

### PR DESCRIPTION
**Pull request by lukasheinrich**
# Description

Adds a nice example how easy Reinterpretations are once we have likelihoods expressed as JSON. Just apply a JSON-patch!

(also adds `jsonpatch` as a dev package)

# Checklist Before Requesting Approver

- [ ] Tests are passing
- [ ] "WIP" removed from the title of the pull request

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@lukasheinrich [This all looks nice](https://github.com/diana-hep/pyhf/blob/recastexample2/docs/examples/notebooks/Recast.ipynb)! However, would you mind adding some cells with Markdown text to explain what's going on? I think to the 3 of us it is clear, but people might not know right away what RECAST means here.

**Comment by lukasheinrich** [comment]
Thanks @matthewfeickert for insisting on this. Added some prose

**Comment by matthewfeickert** [comment]
:smile: Hopefully you didn't find that too pushy. But that looks super great to me, so thanks for adding all of that! :shipit:

**Comment by lukasheinrich** [comment]
not at all, good to finally have a package with somewhat decent docs :-p

**Pull request merged**
