### PR TITLE
Add shapefactor to accepted modifications

### PR DESCRIPTION
**Pull request by matthewfeickert**
Needed to complete #119 (`spec_2bin_2channel_coupledshapefactor`)

# Checklist Before Requesting Approver

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request

### CODE REVIEW

**Comment by matthewfeickert** [comment]
I'm assuming that there wasn't anything else needed, but I thought I'd have you check first instead of just throwing it into #119.

**Comment by matthewfeickert** [comment]
@lukasheinrich, as @kratsg has approved this and was the one to write the schema I'm going to merge this in so we can get #119 done tonight. This is bad manners to not wait for your feedback, but my assumption is that you won't mind in this situation.

**Comment by kratsg** [comment]
> This is bad manners/teamwork on my end to not wait for your feedback, but my assumption is that you won't mind in this situation.

Tbh, it was probably a small oversight on my part. I know @lukasheinrich and I have plans at least later to migrate the schema into separate definitions for each modifier, but this is ok for now.

**Comment by matthewfeickert** [comment]
Sounds good. If this is going to get all cleaned up later that's great.

**Comment by lukasheinrich** [comment]
no worries. looks fine

**Pull request merged**
