### PR TITLE
Insert the POI parameter correctly using POI index in opt_tflow

### PR DESCRIPTION
**Pull request by kratsg**
# Description

`opt_tflow` doesn't insert the POI correctly. Assumed that it was the first one in the list of parameters, but might not always be the case. Need to respect the ordering.

Thanks to @dantrim for providing an example that found the bug.

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

### CODE REVIEW

**Comment by lukasheinrich** [comment]
we should add a test that would make this fail, .. 


```
    spec = {
        'channels': [
            {
                'name': 'singlechannel',
                'samples': [
                    {
                        'name': 'signal',
                        'data': source['bindata']['sig'],
                        'modifiers': [
                            {
                                'name': 'mu',
                                'type': 'normfactor',
                                'data': None
                            }
                        ]
                    },
                    {
                        'name': 'background',
                        'data': source['bindata']['bkg'],
                        'modifiers': [
                            {
                                'name': 'bkg_norm',
                                'type': 'normsys',
                                'data': {'lo': 0.90, 'hi': 1.10}
                            }
                        ]
                    }
                ]
            }
        ]
    }
```

if we change the order of normsys and normfactor it should be covering that case

**Comment by lukasheinrich** [comment]
I added a test which I verified would fail if @kratsg's fix is not applied.

**Comment by lukasheinrich** [comment]
thanks @dantrim for the example!

**Comment by matthewfeickert** [comment]
Excellent that a test has been added too! :)

**Pull request merged**
